import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { FileText, RefreshCw, Calendar, TrendingUp, Clock, Sparkles } from "lucide-react";

interface WeeklyReport {
  id: string;
  week_start: string;
  week_end: string;
  total_actions: number;
  success_rate: number;
  avg_quality_score: number;
  total_cost_usd: number;
  top_performing_agent: string | null;
  top_performing_tool: string | null;
  key_learnings: string | null;
  recommendations: string | null;
  created_at: string;
}

export default function WeeklyReports() {
  const [reports, setReports] = useState<WeeklyReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<WeeklyReport | null>(null);

  const fetchReports = async () => {
    setLoading(true);
    const { data } = await supabase
      .from("weekly_learning_reports")
      .select("id, week_start, week_end, total_actions, success_rate, avg_quality_score, total_cost_usd, top_performing_agent, top_performing_tool, key_learnings, recommendations, created_at")
      .order("week_start", { ascending: false })
      .limit(12);
    if (data) {
      setReports(data);
      if (data.length > 0 && !selected) setSelected(data[0]);
    }
    setLoading(false);
  };

  useEffect(() => { fetchReports(); }, []);

  const fmt = (n: number | undefined, d = 1) => n !== undefined ? n.toFixed(d) : "—";

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="p-2 rounded-lg bg-emerald-500/15 border border-emerald-500/25">
              <FileText className="w-4 h-4 text-emerald-400" />
            </div>
            <h1 className="text-xl font-semibold text-slate-100">Weekly Reports</h1>
            <Badge className="bg-emerald-500/15 text-emerald-300 border border-emerald-500/30 text-xs">
              Monday 2AM
            </Badge>
          </div>
          <p className="text-sm text-slate-500">n8n automated weekly learning reports — generated by Learning Brain Dify agent</p>
        </div>
        <Button size="sm" variant="ghost" onClick={fetchReports} disabled={loading}
          className="h-8 w-8 p-0 text-slate-400 hover:text-slate-200">
          <RefreshCw className={cn("w-4 h-4", loading && "animate-spin")} />
        </Button>
      </div>

      {loading ? (
        <div className="flex items-center gap-2 text-slate-500 text-sm">
          <div className="w-4 h-4 border border-slate-600 border-t-emerald-400 rounded-full animate-spin" />
          Loading reports...
        </div>
      ) : reports.length === 0 ? (
        <div className="bg-slate-900/60 border border-slate-800/60 rounded-xl p-8 text-center">
          <FileText className="w-10 h-10 text-slate-700 mx-auto mb-3" />
          <p className="text-sm text-slate-500">No weekly reports yet</p>
          <p className="text-xs text-slate-600 mt-1">First report will be generated Monday at 2AM UTC</p>
        </div>
      ) : (
        <div className="grid grid-cols-3 gap-4">
          {/* Report list */}
          <div className="space-y-2">
            {reports.map((r) => (
              <button key={r.id} onClick={() => setSelected(r)}
                className={cn(
                  "w-full text-left p-3 rounded-xl border transition-all",
                  selected?.id === r.id
                    ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-300"
                    : "bg-slate-900/60 border-slate-800/60 text-slate-400 hover:text-slate-200 hover:border-slate-700"
                )}>
                <div className="flex items-center gap-2 mb-1">
                  <Calendar className="w-3 h-3" />
                  <span className="text-xs font-medium">
                    {new Date(r.week_start).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                    {" — "}
                    {new Date(r.week_end).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                  </span>
                </div>
                <div className="flex items-center gap-3 text-[10px] text-slate-500">
                  <span>{r.total_actions} actions</span>
                  <span>{fmt(r.success_rate)}% success</span>
                </div>
              </button>
            ))}
          </div>

          {/* Report detail */}
          {selected && (
            <div className="col-span-2 bg-slate-900/60 border border-slate-800/60 rounded-xl p-5 space-y-4">
              <div className="flex items-center justify-between">
                <h2 className="text-sm font-semibold text-slate-100 flex items-center gap-2">
                  <Clock className="w-4 h-4 text-emerald-400" />
                  Week of {new Date(selected.week_start).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
                </h2>
              </div>

              <div className="grid grid-cols-4 gap-3">
                {[
                  { label: "Actions", value: selected.total_actions.toLocaleString(), color: "text-emerald-400" },
                  { label: "Success", value: `${fmt(selected.success_rate)}%`, color: "text-emerald-400" },
                  { label: "Quality", value: `${fmt(selected.avg_quality_score)}/10`, color: "text-amber-400" },
                  { label: "Cost", value: `$${fmt(selected.total_cost_usd, 4)}`, color: "text-rose-400" },
                ].map(k => (
                  <div key={k.label} className="bg-slate-800/40 rounded-lg p-3">
                    <p className="text-[10px] text-slate-500 mb-1">{k.label}</p>
                    <p className={cn("text-lg font-bold", k.color)}>{k.value}</p>
                  </div>
                ))}
              </div>

              {(selected.top_performing_agent || selected.top_performing_tool) && (
                <div className="grid grid-cols-2 gap-3">
                  {selected.top_performing_agent && (
                    <div className="bg-slate-800/40 rounded-lg p-3">
                      <p className="text-[10px] text-slate-500 mb-1">Top Agent</p>
                      <p className="text-xs font-medium text-violet-400">{selected.top_performing_agent}</p>
                    </div>
                  )}
                  {selected.top_performing_tool && (
                    <div className="bg-slate-800/40 rounded-lg p-3">
                      <p className="text-[10px] text-slate-500 mb-1">Top Tool</p>
                      <p className="text-xs font-medium text-blue-400">{selected.top_performing_tool}</p>
                    </div>
                  )}
                </div>
              )}

              {selected.key_learnings && (
                <div>
                  <p className="text-xs font-medium text-slate-400 mb-2 flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-amber-400" /> Key Learnings
                  </p>
                  <p className="text-xs text-slate-400 leading-relaxed bg-slate-800/30 rounded-lg p-3">
                    {selected.key_learnings}
                  </p>
                </div>
              )}

              {selected.recommendations && (
                <div>
                  <p className="text-xs font-medium text-slate-400 mb-2 flex items-center gap-1.5">
                    <TrendingUp className="w-3.5 h-3.5 text-emerald-400" /> Recommendations
                  </p>
                  <p className="text-xs text-slate-400 leading-relaxed bg-slate-800/30 rounded-lg p-3">
                    {selected.recommendations}
                  </p>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
